import os
import sys
import logging

logger = logging.getLogger(__name__)

TIERS = [
    {
        "name": "Lightweight (1B-3B models)",
        "min_ram": 4,
        "models": {"general": "llama3.2:1b", "coding": "qwen2.5-coder:1.5b", "image": "llava"},
        "desc": "Best for older machines or 4-8GB RAM. Fast responses, basic capability.",
    },
    {
        "name": "Standard (7B-8B models)",
        "min_ram": 8,
        "models": {"general": "llama3.2:3b", "coding": "qwen2.5-coder:7b", "image": "llava"},
        "desc": "Good balance of speed and quality. Recommended for 8-16GB RAM.",
    },
    {
        "name": "Large (13B-14B models)",
        "min_ram": 16,
        "models": {"general": "llama3.1:8b", "coding": "deepseek-coder:6.7b", "image": "llava"},
        "desc": "High quality responses. Recommended for 16-32GB RAM.",
    },
    {
        "name": "Heavy (30B+ models)",
        "min_ram": 24,
        "models": {"general": "mixtral:8x7b", "coding": "codellama:13b", "image": "llava"},
        "desc": "Best quality, needs 24GB+ RAM or GPU acceleration.",
    },
]

DOTENV_BOILERPLATE = """# ── Autogenerated by JARVIS Setup Wizard ────────────────────────────
JARVIS_SETUP_DONE=true

# ── LLM Provider ──────────────────────────────────────────────────────
LLM_PROVIDER=ollama
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_MODEL={general_model}

# ── Brain Router: Per-task model routing ──────────────────────────────
CODING_PROVIDER=ollama
CODING_MODEL={coding_model}
CREATIVE_PROVIDER=ollama
CREATIVE_MODEL={general_model}
ANALYSIS_PROVIDER=ollama
ANALYSIS_MODEL={general_model}
RESEARCH_PROVIDER=ollama
RESEARCH_MODEL={general_model}
IMAGE_PROVIDER=ollama
IMAGE_MODEL={image_model}

# ── Speech-to-Text ────────────────────────────────────────────────────
STT_MODEL_SHORT=tiny.en
STT_MODEL_LONG=medium.en
STT_LONG_THRESHOLD=3.0
STT_LOW_CONF_THRESHOLD=0.6
STT_THREADS=2
WHISPER_LANGUAGE=en

# ── Text-to-Speech ────────────────────────────────────────────────────
TTS_PROVIDER=piper

# ── Browser ───────────────────────────────────────────────────────────
USE_OBSCURA=false
OBSCURA_PORT=9222

# ── User ──────────────────────────────────────────────────────────────
USER_TITLE={user_title}

# ── Advanced ──────────────────────────────────────────────────────────
LOG_LEVEL=INFO

# ── Paid API Keys (Optional — leave blank to use only free/local) ────
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
"""


def _get_input(prompt: str, default: str = "") -> str:
    try:
        val = input(prompt).strip()
        return val if val else default
    except (EOFError, KeyboardInterrupt):
        return default


def _get_yes_no(prompt: str, default: bool = True) -> bool:
    default_str = "Y/n" if default else "y/N"
    val = _get_input(f"{prompt} [{default_str}]: ", "y" if default else "n")
    return val.lower() in ("y", "yes", "true", "1", "")


def _detect_system_specs() -> dict:
    try:
        from core.hardware_checker import get_system_specs
        specs = get_system_specs()
        logger.info(f"Detected specs: {specs.get('ram_gb')}GB RAM, "
                     f"{len(specs.get('gpus', []))} GPU(s), "
                     f"max VRAM: {specs.get('max_vram_gb')}GB")
        return specs
    except Exception as e:
        logger.warning(f"Hardware detection failed: {e}")
        return {"ram_gb": 0, "gpus": [], "max_vram_gb": 0}


def _suggest_tier(specs: dict) -> dict | None:
    ram = specs.get("ram_gb", 0)
    vram = specs.get("max_vram_gb", 0)
    effective_ram = max(ram, vram * 4)

    best = None
    for tier in TIERS:
        if effective_ram >= tier["min_ram"]:
            best = tier
    return best


def _print_header():
    print("=" * 65)
    print("  JARVIS Setup Wizard")
    print("  Let's configure JARVIS for your system.")
    print("=" * 65)


def _print_specs(specs: dict):
    print(f"\n  System Specs Detected:")
    print(f"    RAM: {specs.get('ram_gb', 'unknown')} GB")
    gpus = specs.get("gpus", [])
    if gpus:
        for gpu in gpus:
            print(f"    GPU: {gpu['name']} ({gpu['vram_gb']} GB VRAM)")
    else:
        print(f"    GPU: None detected (CPU-only mode)")
    print()


def _print_tier_info(tier: dict):
    print(f"\n  Recommended Tier: {tier['name']}")
    print(f"    {tier['desc']}")
    print(f"    Models: General={tier['models']['general']}, "
          f"Coding={tier['models']['coding']}, Image={tier['models']['image']}")


def _print_tier_options():
    print("\n  Available Tiers:")
    for i, tier in enumerate(TIERS, 1):
        print(f"    {i}. {tier['name']} ({tier['min_ram']}GB+ RAM)")
        print(f"       {tier['desc']}")


def _ask_paid_apis() -> dict:
    api_keys = {}
    print("\n  ── Optional: Paid API Keys ──")
    print("  JARVIS works 100% free and local with no API keys.")
    print("  You can optionally add paid API keys for higher quality on some tasks.")
    print("  Leave blank to skip any key.\n")

    key_defs = [
        ("OPENAI_API_KEY", "OpenAI (GPT-4, DALL-E)"),
        ("ANTHROPIC_API_KEY", "Anthropic (Claude)"),
    ]
    for var, label in key_defs:
        val = _get_input(f"  {label} key (or press Enter to skip): ")
        if val:
            api_keys[var] = val

    return api_keys


def _write_env(tier: dict, api_keys: dict, user_title: str):
    content = DOTENV_BOILERPLATE.format(
        general_model=tier["models"]["general"],
        coding_model=tier["models"]["coding"],
        image_model=tier["models"]["image"],
        user_title=user_title,
    )

    if api_keys:
        content += "\n# ── User-Provided API Keys ──────────────────────────────\n"
        for var, val in api_keys.items():
            content += f"{var}={val}\n"

    env_path = ".env"
    try:
        with open(env_path, "w") as f:
            f.write(content)
        print(f"\n  Configuration saved to {os.path.abspath(env_path)}")
    except Exception as e:
        logger.error(f"Failed to write .env: {e}")
        print(f"\n  ERROR: Could not write .env file: {e}")
        return False

    return True


def run_setup_wizard(env_path: str = ".env") -> bool:
    _print_header()

    specs = _detect_system_specs()
    _print_specs(specs)

    suggested = _suggest_tier(specs)
    if suggested:
        _print_tier_info(suggested)
    else:
        print("\n  Your system appears to have limited resources.")
        print("  The Lightweight tier will be used by default.")

    if not _get_yes_no("\n  Accept this recommendation?", True):
        _print_tier_options()
        choice = _get_input("  Enter tier number (1-4) or press Enter for default: ", "1")
        try:
            idx = max(0, min(int(choice) - 1, len(TIERS) - 1))
            suggested = TIERS[idx]
        except (ValueError, IndexError):
            suggested = suggested or TIERS[0]
        print(f"\n  Selected: {suggested['name']}")

    user_title = _get_input("\n  What should JARVIS call you? (default: sir): ", "sir")

    api_keys = _ask_paid_apis()

    print("\n" + "=" * 65)
    print("  Summary:")
    print(f"    Tier: {suggested['name']}")
    print(f"    General model: {suggested['models']['general']}")
    print(f"    Coding model: {suggested['models']['coding']}")
    print(f"    Call you: {user_title}")
    print(f"    Paid APIs configured: {len(api_keys)}")
    print("=" * 65)

    if not _get_yes_no("\n  Apply this configuration?", True):
        print("\n  Setup cancelled. No changes made.")
        return False

    return _write_env(suggested, api_keys, user_title)


def is_setup_done(env_path: str = ".env") -> bool:
    if not os.path.exists(env_path):
        return False
    try:
        from dotenv import load_dotenv
        load_dotenv(env_path, override=True)
        return os.environ.get("JARVIS_SETUP_DONE", "").lower() == "true"
    except Exception:
        return False


def needs_setup(env_path: str = ".env") -> bool:
    return not is_setup_done(env_path)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    run_setup_wizard()
