import os
import subprocess
import logging
import requests
import zipfile
import io
import shutil
from pathlib import Path

logger = logging.getLogger(__name__)

class PiperTTS:
    """
    Neural Text-to-Speech using Piper (ONNX).
    Provides high-quality, local, low-latency speech.
    """
    PIPER_ZIP_URL = "https://github.com/rhasspy/piper/releases/download/2023.11.14-2/piper_windows_amd64.zip"
    VOICE_URL = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium/en_GB-alan-medium.onnx"
    CONFIG_URL = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium/en_GB-alan-medium.onnx.json"
    
    def __init__(self, base_dir: str = "bin/piper"):
        self.base_dir = Path(base_dir)
        self.exe_path = self.base_dir / "piper" / "piper.exe"
        self.model_path = self.base_dir / "en_GB-alan-medium.onnx"
        self._initialized = False

    def ensure_installed(self):
        """Downloads and extracts Piper and the voice model if missing."""
        if self._initialized:
            return True
            
        try:
            os.makedirs(self.base_dir, exist_ok=True)
            
            # 1. Download Piper Binary
            if not self.exe_path.exists():
                logger.info("Downloading Piper TTS engine...")
                resp = requests.get(self.PIPER_ZIP_URL, timeout=60)
                resp.raise_for_status()
                with zipfile.ZipFile(io.BytesIO(resp.content)) as zip_ref:
                    zip_ref.extractall(self.base_dir)
                logger.info("Piper engine extracted.")

            # 2. Download Voice Model
            if not self.model_path.exists():
                logger.info("Downloading neural voice model (Alan)...")
                for url in [self.VOICE_URL, self.CONFIG_URL]:
                    resp = requests.get(url, timeout=60)
                    resp.raise_for_status()
                    filename = url.split("/")[-1]
                    with open(self.base_dir / filename, "wb") as f:
                        f.write(resp.content)
                logger.info("Voice model downloaded.")

            self._initialized = True
            return True
        except Exception as e:
            logger.error(f"Failed to install Piper TTS: {e}")
            return False

    def speak(self, text: str, on_start_playing=None):
        """Synthesizes and plays speech using Piper."""
        if not self.ensure_installed():
            return False

        try:
            # We use PowerShell to play the WAV generated by Piper
            # to avoid adding heavy audio playback dependencies like pygame.
            # Piper writes to stdout, we pipe it to a temporary file or directly to PS.
            
            clean_text = text.replace('"', '').replace("'", "")
            temp_wav = self.base_dir / "speech.wav"
            
            # Run Piper
            cmd = [
                str(self.exe_path),
                "--model", str(self.model_path),
                "--output_file", str(temp_wav)
            ]
            
            process = subprocess.Popen(cmd, stdin=subprocess.PIPE, stderr=subprocess.DEVNULL)
            process.communicate(input=clean_text.encode('utf-8'))
            
            if temp_wav.exists():
                # Trigger callback right before actual playback
                if on_start_playing:
                    on_start_playing()
                # Play using PowerShell
                ps_cmd = f"Add-Type -AssemblyName System.Media; $player = New-Object System.Media.SoundPlayer('{temp_wav}'); $player.PlaySync()"
                subprocess.run(["powershell", "-Command", ps_cmd], capture_output=True)
                return True
        except Exception as e:
            logger.error(f"Piper speak failed: {e}")
        return False


_PIPER_INSTANCE = None

def get_piper_tts() -> PiperTTS:
    global _PIPER_INSTANCE
    if _PIPER_INSTANCE is None:
        _PIPER_INSTANCE = PiperTTS()
    return _PIPER_INSTANCE
